info_dir=share/info
info_files=(bash.info)

post_install() {
  [ -x bin/install-info ] || return 0
  for f in ${info_files[@]}; do
    bin/install-info ${info_dir}/$f.gz ${info_dir}/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  [ -x bin/install-info ] || return 0
  for f in ${info_files[@]}; do
    bin/install-info --delete ${info_dir}/$f.gz ${info_dir}/dir 2> /dev/null
  done
}
