infodir=/share/info
filelist=(ipc.info.gz)

post_install() {
 [ -x bin/install-info ] || return 0
 for file in ${filelist[@]}; do
    bin/install-info $infodir/$file $infodir/dir 2> /dev/null
 done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
 [ -x bin/install-info ] || return 0
  for file in ${filelist[@]}; do
    bin/install-info --delete $infodir/$file $infodir/dir 2> /dev/null
  done
}

