post_install() {
  echo "   "
  echo "   "
  echo "  +--------------------------------------------------+"
  echo "  |                    JKProcFS                      |"
  echo "  |                                                  |"
  echo "  |   If you want to actually use jkprocfs, then you |"
  echo "  | must first start it with a command like          |"
  echo "  |                                                  |"
  echo "  | settrans -fgap /proc /hurd/jkprocfs --compatible |"
  echo "  |                                                  |"
  echo "  |   ( run as root )                                |"
  echo "  +--------------------------------------------------+"
  echo "   "
  echo "   "
}

post_upgrade() {
  echo "   "
  echo "   "
  echo "  +--------------------------------------------------+"
  echo "  |                    JKProcFS                      |"
  echo "  |                                                  |"
  echo "  |   You should probably restart JKProcFS now by    |"
  echo "  | running a command like                           |"
  echo "  |                                                  |"
  echo "  | settrans -fgap /proc /hurd/jkprocfs --compatible |"
  echo "  |                                                  |"
  echo "  |   ( run as root )                                |"
  echo "  +--------------------------------------------------+"
  echo "   "
  echo "   "
}

