#!/bin/sh

# pipes and login
settrans -cg /servers/socket/1 /hurd/pflocal
settrans -cg /servers/password /hurd/password

# create the needed devices
cd /dev
MAKEDEV std vcs tty1 tty2 tty3 tty4 tty5 tty6
MAKEDEV hd0 hd0s1

