#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting Syslog-NG"
    [ ! -f /var/run/syslog-ng.pid ] && /sbin/syslog-ng
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon syslog-ng
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Syslog-NG"
    [ -f /var/run/syslog-ng.pid ]  && kill `cat /var/run/syslog-ng.pid` &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm -f /var/run/syslog-ng.pid
#     Removing stale syslog-ng.persist file. It's new location, as of 2.0.6-1, is /var/lib/syslog-ng/
      rm -f /var/syslog-ng.persist
      rm_daemon syslog-ng
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
